gender_prompts = {
    'image consists of a woman, girl, female': 'female',
    "image consists of a female human facing away": 'female',
    "image consists of a female human laying on her side": 'female',
    "image consists of a woman facing sideways": 'female',
    "image consists of a man, boy, male": 'male',
    "image consists of a male human facing away": 'male',
    "image consists of a male human laying on his side": 'male',
    "image consists of a man facing sideways": 'male',
    "image consists of a body part": 'unknown',
    "a photo of unidentified object": 'unknown'
}

age_prompts = {
    "image consists of a face of an adorable sweet baby girl, one year old, infant girl": "infant",
    "image consists of a face of a sweet cute baby toddler girl": "infant",
    "image consists of a face of a cute little girl, young child, pre-teen, female kid": "kid",
    "image consists of a face of a playful child, kid": "kid",
    "image consists of a child's face partially hidden, obscure face of a girl": "kid",
    "image consists of a face of a girl": "teen",
    "image consists of a face of a young teenage girl, adolescent, female teen": "teen",
    "image consists of a face of a female high school student": "teen",
    "image consists of a face of a teen girl with makeup": "teen",
    "image consists of a face of a youth, juvenile rebellious teen, beautiful young woman": "adult",
    "image consists of a teen's face partially hidden, obscure face of a female teen": "teen",
    "image consists of a face of a female lady adult, grown-up woman": "adult",
    "image consists of a face of a female college student with makeup, lady": "adult",
    "image consists of a face of a woman, lady": "adult",
    "image consists of a face of a female adult, mature lady, grown-up, middle-age woman, graceful "
    "sophisticated woman": "adult",
    "image consists of a adult's face partially hidden, obscure face of a woman": "adult",
    "image consists of a face of a sweet baby boy, one year old, infant boy": "infant",
    "image consists of a face of a cute baby boy, handsome toddler boy": "infant",
    "image consists of a face of a little handsome boy, young child, pre-teen, male kid": "kid",
    "image consists of a face of a boy": "kid",
    "image consists of a child's face partially hidden, obscure face of a boy": "kid",
    "image consists of a face of a young teenage boy, adolescent, male teen": "teen",
    "image consists of a face of a male high school student": "teen",
    "image consists of a face of a teen jock, high school athlete": "teen",
    "image consists of a face of a youth, juvenile rebellious teen, immature young man": "adult",
    "image consists of a teen's face partially hidden, obscure face of a male teen": "teen",
    "image consists of a face of a male adult, grown-up man": "adult",
    "image consists of a face of a male college student": "adult",
    "image consists of a face of a man": "adult",
    "image consists of a face of a male adult, mature gentlemen, grown-up, middle-age man, man with "
    "facial hair": "adult",
    "a photo of unidentified object": 'unknown',
    "a photo of other": "unknown"}
